/**
 * RAL color catalog — complete RAL Classic palette (213 colors).
 *
 * Each entry carries:
 *  - code:   RAL reference (e.g., "RAL 9005")
 *  - name:   French human name
 *  - hex:    approximate sRGB hex for UI preview (not for print/spec matching)
 *  - family: grouping used by the picker (jaune, orange, rouge, violet, bleu,
 *            vert, gris, brun, noir, blanc)
 *  - popular: whether this color is in the "most popular" shortlist surfaced
 *             by the homepage marquee and quick-filter chips.
 */

export type RALFamily =
  | "jaune"
  | "orange"
  | "rouge"
  | "violet"
  | "bleu"
  | "vert"
  | "gris"
  | "brun"
  | "noir"
  | "blanc";

export interface RALColor {
  code: string;
  name: string;
  hex: string;
  family: RALFamily;
  popular?: boolean;
}

export const RAL_FAMILIES: { key: RALFamily; label: string; hex: string }[] = [
  { key: "jaune", label: "Jaune", hex: "#F4C430" },
  { key: "orange", label: "Orange", hex: "#E85D2C" },
  { key: "rouge", label: "Rouge", hex: "#B32428" },
  { key: "violet", label: "Violet", hex: "#6A3B6A" },
  { key: "bleu", label: "Bleu", hex: "#1D4E89" },
  { key: "vert", label: "Vert", hex: "#2E7D32" },
  { key: "gris", label: "Gris", hex: "#6C6F70" },
  { key: "brun", label: "Brun", hex: "#6B4423" },
  { key: "noir", label: "Noir", hex: "#1C1C1C" },
  { key: "blanc", label: "Blanc", hex: "#F4F4F0" },
];

export const RAL_COLORS: RALColor[] = [
  // ── Jaunes (RAL 1000–1037) ──────────────────────────────────────
  { code: "RAL 1000", name: "Beige vert", hex: "#BEBD7F", family: "jaune" },
  { code: "RAL 1001", name: "Beige", hex: "#C2B078", family: "jaune" },
  { code: "RAL 1002", name: "Jaune sable", hex: "#C6A961", family: "jaune" },
  { code: "RAL 1003", name: "Jaune signalisation", hex: "#F7BA0B", family: "jaune", popular: true },
  { code: "RAL 1004", name: "Jaune or", hex: "#CDA434", family: "jaune" },
  { code: "RAL 1005", name: "Jaune miel", hex: "#A98307", family: "jaune" },
  { code: "RAL 1006", name: "Jaune maïs", hex: "#E4A010", family: "jaune" },
  { code: "RAL 1007", name: "Jaune narcisse", hex: "#E88C00", family: "jaune" },
  { code: "RAL 1011", name: "Beige brun", hex: "#8D8165", family: "jaune" },
  { code: "RAL 1012", name: "Jaune citron", hex: "#C7B446", family: "jaune" },
  { code: "RAL 1013", name: "Blanc perlé", hex: "#EAE6CA", family: "jaune" },
  { code: "RAL 1014", name: "Ivoire", hex: "#E1CC4F", family: "jaune" },
  { code: "RAL 1015", name: "Ivoire clair", hex: "#E6D690", family: "jaune" },
  { code: "RAL 1016", name: "Jaune soufre", hex: "#EDFF21", family: "jaune" },
  { code: "RAL 1017", name: "Jaune safran", hex: "#F5D033", family: "jaune" },
  { code: "RAL 1018", name: "Jaune zinc", hex: "#F8F32B", family: "jaune" },
  { code: "RAL 1019", name: "Beige gris", hex: "#9E9764", family: "jaune" },
  { code: "RAL 1020", name: "Jaune olive", hex: "#999950", family: "jaune" },
  { code: "RAL 1021", name: "Jaune colza", hex: "#EEC900", family: "jaune" },
  { code: "RAL 1023", name: "Jaune signalisation", hex: "#F0CA00", family: "jaune" },
  { code: "RAL 1024", name: "Jaune ocre", hex: "#AEA04B", family: "jaune" },
  { code: "RAL 1026", name: "Jaune brillant", hex: "#FFFF00", family: "jaune" },
  { code: "RAL 1027", name: "Jaune curry", hex: "#9D9101", family: "jaune" },
  { code: "RAL 1028", name: "Jaune melon", hex: "#F4A900", family: "jaune" },
  { code: "RAL 1032", name: "Jaune genêt", hex: "#D6AE01", family: "jaune" },
  { code: "RAL 1033", name: "Jaune dahlia", hex: "#F3A505", family: "jaune" },
  { code: "RAL 1034", name: "Jaune pastel", hex: "#EFA94A", family: "jaune" },
  { code: "RAL 1035", name: "Beige nacré", hex: "#6A5D4D", family: "jaune" },
  { code: "RAL 1036", name: "Or nacré", hex: "#705335", family: "jaune" },
  { code: "RAL 1037", name: "Jaune soleil", hex: "#F09F00", family: "jaune" },
  // ── Oranges (RAL 2000–2013) ─────────────────────────────────────
  { code: "RAL 2000", name: "Orangé jaune", hex: "#ED760E", family: "orange" },
  { code: "RAL 2001", name: "Orangé rouge", hex: "#C93C20", family: "orange" },
  { code: "RAL 2002", name: "Orangé sang", hex: "#CB2821", family: "orange" },
  { code: "RAL 2003", name: "Orangé pastel", hex: "#FF7514", family: "orange" },
  { code: "RAL 2004", name: "Orangé pur", hex: "#F44611", family: "orange", popular: true },
  { code: "RAL 2005", name: "Orangé brillant", hex: "#FF2301", family: "orange" },
  { code: "RAL 2007", name: "Orangé brillant clair", hex: "#FFA420", family: "orange" },
  { code: "RAL 2008", name: "Orangé rouge clair", hex: "#F3752C", family: "orange" },
  { code: "RAL 2009", name: "Orangé signalisation", hex: "#E55137", family: "orange" },
  { code: "RAL 2010", name: "Orangé signalisation", hex: "#D56231", family: "orange" },
  { code: "RAL 2011", name: "Orangé foncé", hex: "#D4652F", family: "orange" },
  { code: "RAL 2012", name: "Orangé saumon", hex: "#E55137", family: "orange" },
  { code: "RAL 2013", name: "Orangé nacré", hex: "#C35831", family: "orange" },
  // ── Rouges (RAL 3000–3031) ──────────────────────────────────────
  { code: "RAL 3000", name: "Rouge feu", hex: "#AF2B1E", family: "rouge", popular: true },
  { code: "RAL 3001", name: "Rouge signalisation", hex: "#A52019", family: "rouge" },
  { code: "RAL 3002", name: "Rouge carmin", hex: "#A2231D", family: "rouge" },
  { code: "RAL 3003", name: "Rouge rubis", hex: "#9B111E", family: "rouge" },
  { code: "RAL 3004", name: "Rouge pourpre", hex: "#75151E", family: "rouge" },
  { code: "RAL 3005", name: "Rouge vin", hex: "#5E2129", family: "rouge" },
  { code: "RAL 3007", name: "Rouge noir", hex: "#412227", family: "rouge" },
  { code: "RAL 3009", name: "Rouge oxyde", hex: "#642424", family: "rouge" },
  { code: "RAL 3011", name: "Rouge brun", hex: "#781F19", family: "rouge" },
  { code: "RAL 3012", name: "Rouge beige", hex: "#C1876B", family: "rouge" },
  { code: "RAL 3013", name: "Rouge tomate", hex: "#A12312", family: "rouge" },
  { code: "RAL 3014", name: "Vieux rose", hex: "#D36E70", family: "rouge" },
  { code: "RAL 3015", name: "Rose clair", hex: "#EA899A", family: "rouge" },
  { code: "RAL 3016", name: "Rouge corail", hex: "#B32821", family: "rouge" },
  { code: "RAL 3017", name: "Rosé", hex: "#E63244", family: "rouge" },
  { code: "RAL 3018", name: "Rouge fraise", hex: "#D53032", family: "rouge" },
  { code: "RAL 3020", name: "Rouge signalisation", hex: "#CC0605", family: "rouge", popular: true },
  { code: "RAL 3022", name: "Rouge saumon", hex: "#D95030", family: "rouge" },
  { code: "RAL 3024", name: "Rouge brillant", hex: "#F80000", family: "rouge" },
  { code: "RAL 3026", name: "Rouge brillant clair", hex: "#FE0000", family: "rouge" },
  { code: "RAL 3027", name: "Rouge framboise", hex: "#C51D34", family: "rouge" },
  { code: "RAL 3028", name: "Rouge pur", hex: "#CB3234", family: "rouge" },
  { code: "RAL 3031", name: "Rouge oriental", hex: "#B32428", family: "rouge" },
  // ── Violets (RAL 4001–4012) ─────────────────────────────────────
  { code: "RAL 4001", name: "Lilas rouge", hex: "#6D3F5B", family: "violet" },
  { code: "RAL 4002", name: "Violet rouge", hex: "#922B3E", family: "violet" },
  { code: "RAL 4003", name: "Violet érica", hex: "#C63678", family: "violet" },
  { code: "RAL 4004", name: "Violet bordeaux", hex: "#641C34", family: "violet" },
  { code: "RAL 4005", name: "Lilas bleu", hex: "#6C4675", family: "violet" },
  { code: "RAL 4006", name: "Pourpre signalisation", hex: "#A03472", family: "violet" },
  { code: "RAL 4007", name: "Violet pourpre", hex: "#4A192C", family: "violet" },
  { code: "RAL 4008", name: "Violet signalisation", hex: "#924E7D", family: "violet" },
  { code: "RAL 4009", name: "Violet pastel", hex: "#A18594", family: "violet" },
  { code: "RAL 4010", name: "Télémagenta", hex: "#CF3476", family: "violet" },
  { code: "RAL 4011", name: "Violet nacré", hex: "#8673A1", family: "violet" },
  { code: "RAL 4012", name: "Mûre nacré", hex: "#6C6874", family: "violet" },
  // ── Bleus (RAL 5000–5026) ───────────────────────────────────────
  { code: "RAL 5000", name: "Bleu violet", hex: "#354D73", family: "bleu" },
  { code: "RAL 5001", name: "Bleu vert", hex: "#1F3438", family: "bleu" },
  { code: "RAL 5002", name: "Bleu outremer", hex: "#20214F", family: "bleu" },
  { code: "RAL 5003", name: "Bleu saphir", hex: "#1D1E33", family: "bleu" },
  { code: "RAL 5004", name: "Bleu noir", hex: "#18171C", family: "bleu" },
  { code: "RAL 5005", name: "Bleu signalisation", hex: "#1E3A5F", family: "bleu" },
  { code: "RAL 5007", name: "Bleu brillant", hex: "#3E5F8A", family: "bleu" },
  { code: "RAL 5008", name: "Bleu gris", hex: "#26252D", family: "bleu" },
  { code: "RAL 5009", name: "Bleu azur", hex: "#025669", family: "bleu" },
  { code: "RAL 5010", name: "Bleu gentiane", hex: "#0E294B", family: "bleu", popular: true },
  { code: "RAL 5011", name: "Bleu acier", hex: "#231A24", family: "bleu" },
  { code: "RAL 5012", name: "Bleu clair", hex: "#1E88E5", family: "bleu" },
  { code: "RAL 5013", name: "Bleu cobalt", hex: "#1E213D", family: "bleu" },
  { code: "RAL 5014", name: "Bleu pigeon", hex: "#606E8C", family: "bleu" },
  { code: "RAL 5015", name: "Bleu ciel", hex: "#2271B3", family: "bleu" },
  { code: "RAL 5017", name: "Bleu signalisation", hex: "#063971", family: "bleu" },
  { code: "RAL 5018", name: "Bleu turquoise", hex: "#3F888F", family: "bleu" },
  { code: "RAL 5019", name: "Bleu capri", hex: "#1B5583", family: "bleu" },
  { code: "RAL 5020", name: "Bleu océan", hex: "#1D334A", family: "bleu" },
  { code: "RAL 5021", name: "Bleu d'eau", hex: "#256D7B", family: "bleu" },
  { code: "RAL 5022", name: "Bleu nocturne", hex: "#252850", family: "bleu" },
  { code: "RAL 5023", name: "Bleu distant", hex: "#49678D", family: "bleu" },
  { code: "RAL 5024", name: "Bleu pastel", hex: "#5D9B9B", family: "bleu" },
  { code: "RAL 5025", name: "Bleu nacré gentiane", hex: "#2A6478", family: "bleu" },
  { code: "RAL 5026", name: "Bleu nuit nacré", hex: "#102C54", family: "bleu" },
  // ── Verts (RAL 6000–6038) ───────────────────────────────────────
  { code: "RAL 6000", name: "Vert patine", hex: "#316650", family: "vert" },
  { code: "RAL 6001", name: "Vert émeraude", hex: "#287233", family: "vert" },
  { code: "RAL 6002", name: "Vert feuillage", hex: "#2D572C", family: "vert" },
  { code: "RAL 6003", name: "Vert olive", hex: "#424632", family: "vert" },
  { code: "RAL 6004", name: "Vert bleu", hex: "#1F3A3D", family: "vert" },
  { code: "RAL 6005", name: "Vert mousse", hex: "#0F4336", family: "vert", popular: true },
  { code: "RAL 6006", name: "Olive gris", hex: "#3E3B32", family: "vert" },
  { code: "RAL 6007", name: "Vert bouteille", hex: "#343B29", family: "vert" },
  { code: "RAL 6008", name: "Vert brun", hex: "#39352A", family: "vert" },
  { code: "RAL 6009", name: "Vert sapin", hex: "#27352A", family: "vert" },
  { code: "RAL 6010", name: "Vert herbe", hex: "#35682D", family: "vert" },
  { code: "RAL 6011", name: "Vert réséda", hex: "#587246", family: "vert" },
  { code: "RAL 6012", name: "Vert noir", hex: "#343E40", family: "vert" },
  { code: "RAL 6013", name: "Vert jonc", hex: "#6C7156", family: "vert" },
  { code: "RAL 6014", name: "Olive jaune", hex: "#47402E", family: "vert" },
  { code: "RAL 6015", name: "Olive noir", hex: "#3B3C36", family: "vert" },
  { code: "RAL 6016", name: "Vert turquoise", hex: "#1E5945", family: "vert" },
  { code: "RAL 6017", name: "Vert mai", hex: "#4C9141", family: "vert" },
  { code: "RAL 6018", name: "Vert jaune", hex: "#57A639", family: "vert" },
  { code: "RAL 6019", name: "Vert blanc", hex: "#BDECB6", family: "vert" },
  { code: "RAL 6020", name: "Vert oxyde chromique", hex: "#2E3A23", family: "vert" },
  { code: "RAL 6021", name: "Vert pâle", hex: "#89AC76", family: "vert" },
  { code: "RAL 6022", name: "Olive brun", hex: "#25221B", family: "vert" },
  { code: "RAL 6024", name: "Vert signalisation", hex: "#308446", family: "vert" },
  { code: "RAL 6025", name: "Vert fougère", hex: "#3D642D", family: "vert" },
  { code: "RAL 6026", name: "Vert opale", hex: "#015D52", family: "vert" },
  { code: "RAL 6027", name: "Vert clair", hex: "#84C3BE", family: "vert" },
  { code: "RAL 6028", name: "Vert pin", hex: "#2C5545", family: "vert" },
  { code: "RAL 6029", name: "Vert menthe", hex: "#20603D", family: "vert" },
  { code: "RAL 6032", name: "Vert signalisation", hex: "#317F43", family: "vert" },
  { code: "RAL 6033", name: "Turquoise menthe", hex: "#497E76", family: "vert" },
  { code: "RAL 6034", name: "Turquoise pastel", hex: "#7FB5B5", family: "vert" },
  { code: "RAL 6035", name: "Vert nacré", hex: "#1C542D", family: "vert" },
  { code: "RAL 6036", name: "Vert opale nacré", hex: "#193737", family: "vert" },
  { code: "RAL 6037", name: "Vert pur", hex: "#008F39", family: "vert" },
  { code: "RAL 6038", name: "Vert brillant", hex: "#00BB2D", family: "vert" },
  // ── Gris (RAL 7000–7048) ────────────────────────────────────────
  { code: "RAL 7000", name: "Gris petit-gris", hex: "#78858B", family: "gris" },
  { code: "RAL 7001", name: "Gris argent", hex: "#8A9597", family: "gris" },
  { code: "RAL 7002", name: "Gris olive", hex: "#7E7B52", family: "gris" },
  { code: "RAL 7003", name: "Gris mousse", hex: "#6C7059", family: "gris" },
  { code: "RAL 7004", name: "Gris signalisation", hex: "#969992", family: "gris" },
  { code: "RAL 7005", name: "Gris souris", hex: "#646B63", family: "gris" },
  { code: "RAL 7006", name: "Gris beige", hex: "#6D6552", family: "gris" },
  { code: "RAL 7008", name: "Gris kaki", hex: "#6A5F31", family: "gris" },
  { code: "RAL 7009", name: "Gris vert", hex: "#4D5645", family: "gris" },
  { code: "RAL 7010", name: "Gris tente", hex: "#4C514A", family: "gris" },
  { code: "RAL 7011", name: "Gris fer", hex: "#434B4D", family: "gris" },
  { code: "RAL 7012", name: "Gris basalte", hex: "#4E5754", family: "gris" },
  { code: "RAL 7013", name: "Gris brun", hex: "#464531", family: "gris" },
  { code: "RAL 7015", name: "Gris ardoise", hex: "#434750", family: "gris" },
  { code: "RAL 7016", name: "Gris anthracite", hex: "#293133", family: "gris", popular: true },
  { code: "RAL 7021", name: "Gris noir", hex: "#23282B", family: "gris" },
  { code: "RAL 7022", name: "Gris terre d'ombre", hex: "#332F2C", family: "gris" },
  { code: "RAL 7023", name: "Gris béton", hex: "#686C5E", family: "gris" },
  { code: "RAL 7024", name: "Gris graphite", hex: "#474A51", family: "gris", popular: true },
  { code: "RAL 7026", name: "Gris granit", hex: "#2F353B", family: "gris" },
  { code: "RAL 7030", name: "Gris pierre", hex: "#8B8C7A", family: "gris" },
  { code: "RAL 7031", name: "Gris bleu", hex: "#474B4E", family: "gris" },
  { code: "RAL 7032", name: "Gris silex", hex: "#B8B799", family: "gris" },
  { code: "RAL 7033", name: "Gris ciment", hex: "#7D8471", family: "gris" },
  { code: "RAL 7034", name: "Gris jaune", hex: "#8F8B66", family: "gris" },
  { code: "RAL 7035", name: "Gris clair", hex: "#CBD0CC", family: "gris", popular: true },
  { code: "RAL 7036", name: "Gris platine", hex: "#7F7679", family: "gris" },
  { code: "RAL 7037", name: "Gris poussière", hex: "#7D7F7D", family: "gris" },
  { code: "RAL 7038", name: "Gris agate", hex: "#B5B8B1", family: "gris" },
  { code: "RAL 7039", name: "Gris quartz", hex: "#6C6960", family: "gris" },
  { code: "RAL 7040", name: "Gris fenêtre", hex: "#9DA1AA", family: "gris" },
  { code: "RAL 7042", name: "Gris signalisation A", hex: "#8D948D", family: "gris" },
  { code: "RAL 7043", name: "Gris signalisation B", hex: "#4E5451", family: "gris" },
  { code: "RAL 7044", name: "Gris soie", hex: "#CAC4B0", family: "gris" },
  { code: "RAL 7045", name: "Télégris 1", hex: "#909090", family: "gris" },
  { code: "RAL 7046", name: "Télégris 2", hex: "#82898F", family: "gris" },
  { code: "RAL 7047", name: "Télégris 4", hex: "#D0D0D0", family: "gris" },
  { code: "RAL 7048", name: "Gris souris nacré", hex: "#898176", family: "gris" },
  // ── Bruns (RAL 8000–8029) ───────────────────────────────────────
  { code: "RAL 8000", name: "Brun vert", hex: "#826C34", family: "brun" },
  { code: "RAL 8001", name: "Brun ocre", hex: "#8E402A", family: "brun" },
  { code: "RAL 8002", name: "Brun signalisation", hex: "#6C3B2A", family: "brun" },
  { code: "RAL 8003", name: "Brun argile", hex: "#734222", family: "brun" },
  { code: "RAL 8004", name: "Brun cuivré", hex: "#8D4931", family: "brun" },
  { code: "RAL 8007", name: "Brun fauve", hex: "#59351F", family: "brun" },
  { code: "RAL 8008", name: "Brun olive", hex: "#6F4F28", family: "brun" },
  { code: "RAL 8011", name: "Brun noisette", hex: "#5B3A29", family: "brun" },
  { code: "RAL 8012", name: "Brun rouge", hex: "#592321", family: "brun" },
  { code: "RAL 8014", name: "Brun sépia", hex: "#4A3526", family: "brun" },
  { code: "RAL 8015", name: "Brun marron", hex: "#633A34", family: "brun" },
  { code: "RAL 8016", name: "Brun acajou", hex: "#4C2F27", family: "brun" },
  { code: "RAL 8017", name: "Brun chocolat", hex: "#442F29", family: "brun" },
  { code: "RAL 8019", name: "Brun gris", hex: "#3D3635", family: "brun" },
  { code: "RAL 8022", name: "Brun noir", hex: "#1A1A1A", family: "brun" },
  { code: "RAL 8023", name: "Brun orangé", hex: "#A65E2E", family: "brun" },
  { code: "RAL 8024", name: "Brun beige", hex: "#79553D", family: "brun" },
  { code: "RAL 8025", name: "Brun pâle", hex: "#755C48", family: "brun" },
  { code: "RAL 8028", name: "Brun terre", hex: "#4E3B31", family: "brun" },
  { code: "RAL 8029", name: "Cuivre nacré", hex: "#763C28", family: "brun" },
  // ── Noirs & Blancs (RAL 9001–9023) ──────────────────────────────
  { code: "RAL 9001", name: "Blanc crème", hex: "#FDF4E3", family: "blanc" },
  { code: "RAL 9002", name: "Blanc gris", hex: "#E7EBDA", family: "blanc" },
  { code: "RAL 9003", name: "Blanc signalisation", hex: "#F4F4F4", family: "blanc" },
  { code: "RAL 9004", name: "Noir signalisation", hex: "#282828", family: "noir", popular: true },
  { code: "RAL 9005", name: "Noir foncé", hex: "#0A0A0A", family: "noir", popular: true },
  { code: "RAL 9006", name: "Aluminium blanc", hex: "#A5A5A5", family: "blanc", popular: true },
  { code: "RAL 9007", name: "Aluminium gris", hex: "#8F8F8F", family: "blanc" },
  { code: "RAL 9010", name: "Blanc pur", hex: "#F1ECE1", family: "blanc", popular: true },
  { code: "RAL 9011", name: "Noir graphite", hex: "#1C1C1C", family: "noir" },
  { code: "RAL 9016", name: "Blanc signalisation", hex: "#F6F6F6", family: "blanc", popular: true },
  { code: "RAL 9017", name: "Noir signalisation", hex: "#1E1E1E", family: "noir" },
  { code: "RAL 9018", name: "Blanc papyrus", hex: "#D7D7D7", family: "blanc" },
  { code: "RAL 9022", name: "Gris clair nacré", hex: "#9C9C9C", family: "blanc" },
  { code: "RAL 9023", name: "Gris foncé nacré", hex: "#828282", family: "noir" },
];

export const POPULAR_RAL = RAL_COLORS.filter((c) => c.popular);

export function getColorsByFamily(family: RALFamily): RALColor[] {
  return RAL_COLORS.filter((c) => c.family === family);
}
