/**
 * AUTO-GENERATED by scripts/build-adapta.mjs
 * Do not edit by hand. Run `node scripts/build-adapta.mjs && node scripts/optimize-adapta.mjs`.
 */

export interface AdaptaFinish {
  id: string;
  name: string;
  imageUrl?: string;
}

export interface AdaptaSub {
  id: string;
  name: string;
  description?: string;
  finishes: AdaptaFinish[];
}

export const ADAPTA_PATINA_SUBS: AdaptaSub[] = [
  {
    "id": "plain-oxide-patina",
    "name": "Plain Oxide Patina",
    "description": "Codes RAL revisités en finition oxyde corten authentique.",
    "finishes": [
      {
        "id": "rt-8283-i",
        "name": "RT-8283-I",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rt-8283-i.webp"
      },
      {
        "id": "rt-8281-i",
        "name": "RT-8281-I",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rt-8281-i.webp"
      },
      {
        "id": "rt-8286-i",
        "name": "RT-8286-I",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rt-8286-i.webp"
      },
      {
        "id": "rt-8102-i",
        "name": "RT-8102-I",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rt-8102-i.webp"
      },
      {
        "id": "rt-8107-i",
        "name": "RT-8107-I",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rt-8107-i.webp"
      },
      {
        "id": "rf-8284-xw",
        "name": "RF-8284-XW",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rf-8284-xw.webp"
      },
      {
        "id": "rt-1702-i",
        "name": "RT-1702-I",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rt-1702-i.webp"
      },
      {
        "id": "rf-6296-xw",
        "name": "RF-6296-XW",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rf-6296-xw.webp"
      },
      {
        "id": "df-1536-xw",
        "name": "DF-1536-XW",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/df-1536-xw.webp"
      },
      {
        "id": "rf-6297-xw",
        "name": "RF-6297-XW",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rf-6297-xw.webp"
      },
      {
        "id": "rt-6302-i",
        "name": "RT-6302-I",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rt-6302-i.webp"
      },
      {
        "id": "rf-6300-iw",
        "name": "RF-6300-IW",
        "imageUrl": "/images/collections/adapta/patina/plain-oxide-patina/rf-6300-iw.webp"
      }
    ]
  },
  {
    "id": "tile-patina",
    "name": "Tile Patina",
    "description": "Effets argileux et érodés inspirés des terres cuites millénaires.",
    "finishes": [
      {
        "id": "gentle-erosion",
        "name": "GENTLE EROSION",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/gentle-erosion.webp"
      },
      {
        "id": "resilient-clay",
        "name": "RESILIENT CLAY",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/resilient-clay.webp"
      },
      {
        "id": "latent-hermits",
        "name": "LATENT HERMITS",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/latent-hermits.webp"
      },
      {
        "id": "lost-footprints",
        "name": "LOST FOOTPRINTS",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/lost-footprints.webp"
      },
      {
        "id": "serene-safari",
        "name": "SERENE SAFARI",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/serene-safari.webp"
      },
      {
        "id": "gilt-sunset",
        "name": "GILT SUNSET",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/gilt-sunset.webp"
      },
      {
        "id": "pristine-coves",
        "name": "PRISTINE COVES",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/pristine-coves.webp"
      },
      {
        "id": "top-hand-crafting",
        "name": "TOP HAND-CRAFTING",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/top-hand-crafting.webp"
      },
      {
        "id": "unspoilt-beaches",
        "name": "UNSPOILT BEACHES",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/unspoilt-beaches.webp"
      },
      {
        "id": "dune-plateau",
        "name": "DUNE PLATEAU",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/dune-plateau.webp"
      },
      {
        "id": "soft-peat",
        "name": "SOFT PEAT",
        "imageUrl": "/images/collections/adapta/patina/tile-patina/soft-peat.webp"
      },
      {
        "id": "warm-timanfaya",
        "name": "WARM TIMANFAYA"
      }
    ]
  },
  {
    "id": "oxide-patina-i",
    "name": "Oxide Patina I",
    "description": "Premier opus — tonalités feu, terre et lave figée.",
    "finishes": [
      {
        "id": "land-of-fire",
        "name": "LAND OF FIRE",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/land-of-fire.webp"
      },
      {
        "id": "lethargic-savannah",
        "name": "LETHARGIC SAVANNAH",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/lethargic-savannah.webp"
      },
      {
        "id": "spicy-crater",
        "name": "SPICY CRATER",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/spicy-crater.webp"
      },
      {
        "id": "powerful-twister",
        "name": "POWERFUL TWISTER",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/powerful-twister.webp"
      },
      {
        "id": "effervescent-earth",
        "name": "EFFERVESCENT EARTH",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/effervescent-earth.webp"
      },
      {
        "id": "glowing-slurry",
        "name": "GLOWING SLURRY",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/glowing-slurry.webp"
      },
      {
        "id": "desert-mist",
        "name": "DESERT MIST",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/desert-mist.webp"
      },
      {
        "id": "wildlife-sanctuary",
        "name": "WILDLIFE SANCTUARY",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/wildlife-sanctuary.webp"
      },
      {
        "id": "crowded-oasis",
        "name": "CROWDED OASIS",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/crowded-oasis.webp"
      },
      {
        "id": "musical-waterfall",
        "name": "MUSICAL WATERFALL",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/musical-waterfall.webp"
      },
      {
        "id": "magnificient-shore",
        "name": "MAGNIFICIENT SHORE",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/magnificient-shore.webp"
      },
      {
        "id": "bitter-water",
        "name": "BITTER WATER",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-i/bitter-water.webp"
      }
    ]
  },
  {
    "id": "oxide-patina-ii",
    "name": "Oxide Patina II",
    "description": "Second opus — nuances vertes, cuivrées et minérales.",
    "finishes": [
      {
        "id": "turquoise-copper",
        "name": "TURQUOISE COPPER",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/turquoise-copper.webp"
      },
      {
        "id": "untouched-steppes",
        "name": "UNTOUCHED STEPPES",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/untouched-steppes.webp"
      },
      {
        "id": "quiet-patagonia",
        "name": "QUIET PATAGONIA",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/quiet-patagonia.webp"
      },
      {
        "id": "bright-moss",
        "name": "BRIGHT MOSS",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/bright-moss.webp"
      },
      {
        "id": "lush-vegetation",
        "name": "LUSH VEGETATION",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/lush-vegetation.webp"
      },
      {
        "id": "temperate-rainforest",
        "name": "TEMPERATE RAINFOREST",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/temperate-rainforest.webp"
      },
      {
        "id": "ocean-breeze",
        "name": "OCEAN BREEZE",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/ocean-breeze.webp"
      },
      {
        "id": "tough-everglades",
        "name": "TOUGH EVERGLADES",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/tough-everglades.webp"
      },
      {
        "id": "suspicious-marsh",
        "name": "SUSPICIOUS MARSH",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/suspicious-marsh.webp"
      },
      {
        "id": "golden-soil",
        "name": "GOLDEN SOIL",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/golden-soil.webp"
      },
      {
        "id": "late-afternoon",
        "name": "LATE AFTERNOON",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/late-afternoon.webp"
      },
      {
        "id": "silent-ice",
        "name": "SILENT ICE",
        "imageUrl": "/images/collections/adapta/patina/oxide-patina-ii/silent-ice.webp"
      }
    ]
  },
  {
    "id": "soft-patina",
    "name": "Soft Patina",
    "description": "Douceur poudrée — patines feutrées et voilées.",
    "finishes": [
      {
        "id": "calm-cappadocia",
        "name": "CALM CAPPADOCIA",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/calm-cappadocia.webp"
      },
      {
        "id": "frozen-streams",
        "name": "FROZEN STREAMS",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/frozen-streams.webp"
      },
      {
        "id": "hasty-wind",
        "name": "HASTY WIND",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/hasty-wind.webp"
      },
      {
        "id": "northern-thunder",
        "name": "NORTHERN THUNDER",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/northern-thunder.webp"
      },
      {
        "id": "cold-cliffs",
        "name": "COLD CLIFFS",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/cold-cliffs.webp"
      },
      {
        "id": "waves-crashing",
        "name": "WAVES CRASHING",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/waves-crashing.webp"
      },
      {
        "id": "fringing-reefs",
        "name": "FRINGING REEFS",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/fringing-reefs.webp"
      },
      {
        "id": "sunny-wetland",
        "name": "SUNNY WETLAND",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/sunny-wetland.webp"
      },
      {
        "id": "wild-amazon",
        "name": "WILD AMAZON",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/wild-amazon.webp"
      },
      {
        "id": "outlandish-timbuktu",
        "name": "OUTLANDISH TIMBUKTU",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/outlandish-timbuktu.webp"
      },
      {
        "id": "mysterious-bermudas",
        "name": "MYSTERIOUS BERMUDAS",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/mysterious-bermudas.webp"
      },
      {
        "id": "mangrove-swamp",
        "name": "MANGROVE SWAMP",
        "imageUrl": "/images/collections/adapta/patina/soft-patina/mangrove-swamp.webp"
      }
    ]
  },
  {
    "id": "crystal-patina",
    "name": "Crystal Patina",
    "description": "Effet cristallin translucide sur base métallique.",
    "finishes": [
      {
        "id": "rw-9261-xw",
        "name": "RW-9261-XW",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-9261-xw.webp"
      },
      {
        "id": "rw-9006-xw",
        "name": "RW-9006-XW",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-9006-xw.webp"
      },
      {
        "id": "rw-9007-xw",
        "name": "RW-9007-XW",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-9007-xw.webp"
      },
      {
        "id": "rw-7100-xw",
        "name": "RW-7100-XW",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-7100-xw.webp"
      },
      {
        "id": "rw-1703-xw",
        "name": "RW-1703-XW",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-1703-xw.webp"
      },
      {
        "id": "rw-8285-xw",
        "name": "RW-8285-XW",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-8285-xw.webp"
      },
      {
        "id": "rw-6301",
        "name": "RW-6301",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-6301.webp"
      },
      {
        "id": "rw-1170-xw",
        "name": "RW-1170-XW",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-1170-xw.webp"
      },
      {
        "id": "rw-3197",
        "name": "RW-3197",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-3197.webp"
      },
      {
        "id": "rw-6289",
        "name": "RW-6289",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-6289.webp"
      },
      {
        "id": "rw-6303-xw",
        "name": "RW-6303-XW",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-6303-xw.webp"
      },
      {
        "id": "rw-5228",
        "name": "RW-5228",
        "imageUrl": "/images/collections/adapta/patina/crystal-patina/rw-5228.webp"
      }
    ]
  }
];

export const ADAPTA_POLARIS_SUBS: AdaptaSub[] = [
  {
    "id": "chamaleon",
    "name": "Chamaleon",
    "description": "Métalliques caméléons — reflets qui changent selon l'angle.",
    "finishes": [
      {
        "id": "rb-7182-i",
        "name": "RB-7182-I",
        "imageUrl": "/images/collections/adapta/polaris/chamaleon/rb-7182-i.webp"
      },
      {
        "id": "rb-5112-i",
        "name": "RB-5112-I",
        "imageUrl": "/images/collections/adapta/polaris/chamaleon/rb-5112-i.webp"
      },
      {
        "id": "rb-1101-i",
        "name": "RB-1101-I",
        "imageUrl": "/images/collections/adapta/polaris/chamaleon/rb-1101-i.webp"
      },
      {
        "id": "rb-2108-i",
        "name": "RB-2108-I",
        "imageUrl": "/images/collections/adapta/polaris/chamaleon/rb-2108-i.webp"
      },
      {
        "id": "rb-6123-i",
        "name": "RB-6123-I",
        "imageUrl": "/images/collections/adapta/polaris/chamaleon/rb-6123-i.webp"
      },
      {
        "id": "rb-7183-i",
        "name": "RB-7183-I",
        "imageUrl": "/images/collections/adapta/polaris/chamaleon/rb-7183-i.webp"
      }
    ]
  },
  {
    "id": "sculptur",
    "name": "Sculptur",
    "description": "Granulations métalliques — grain sculpté haute définition.",
    "finishes": [
      {
        "id": "rl-1501-xw",
        "name": "RL-1501-XW",
        "imageUrl": "/images/collections/adapta/polaris/sculptur/rl-1501-xw.webp"
      },
      {
        "id": "rl-1502-xw",
        "name": "RL-1502-XW",
        "imageUrl": "/images/collections/adapta/polaris/sculptur/rl-1502-xw.webp"
      },
      {
        "id": "rl-3104-xw",
        "name": "RL-3104-XW",
        "imageUrl": "/images/collections/adapta/polaris/sculptur/rl-3104-xw.webp"
      },
      {
        "id": "rl-5106-xw",
        "name": "RL-5106-XW",
        "imageUrl": "/images/collections/adapta/polaris/sculptur/rl-5106-xw.webp"
      },
      {
        "id": "rl-6108-xw",
        "name": "RL-6108-XW",
        "imageUrl": "/images/collections/adapta/polaris/sculptur/rl-6108-xw.webp"
      },
      {
        "id": "rl-7117-xw",
        "name": "RL-7117-XW",
        "imageUrl": "/images/collections/adapta/polaris/sculptur/rl-7117-xw.webp"
      }
    ]
  },
  {
    "id": "boreal",
    "name": "Boreal",
    "description": "Effets aurore boréale — profondeurs iridescentes.",
    "finishes": [
      {
        "id": "rh-5107",
        "name": "RH-5107",
        "imageUrl": "/images/collections/adapta/polaris/boreal/rh-5107.webp"
      },
      {
        "id": "rh-6127",
        "name": "RH-6127",
        "imageUrl": "/images/collections/adapta/polaris/boreal/rh-6127.webp"
      },
      {
        "id": "rh-7184",
        "name": "RH-7184",
        "imageUrl": "/images/collections/adapta/polaris/boreal/rh-7184.webp"
      },
      {
        "id": "rh-1515",
        "name": "RH-1515",
        "imageUrl": "/images/collections/adapta/polaris/boreal/rh-1515.webp"
      }
    ]
  },
  {
    "id": "orion",
    "name": "Orion",
    "description": "Métaux sombres — finitions brossées constellation.",
    "finishes": [
      {
        "id": "rx-7188-xw",
        "name": "RX-7188-XW",
        "imageUrl": "/images/collections/adapta/polaris/orion/rx-7188-xw.webp"
      },
      {
        "id": "rx-7190-xw",
        "name": "RX-7190-XW",
        "imageUrl": "/images/collections/adapta/polaris/orion/rx-7190-xw.webp"
      },
      {
        "id": "rx-1514-xw",
        "name": "RX-1514-XW",
        "imageUrl": "/images/collections/adapta/polaris/orion/rx-1514-xw.webp"
      },
      {
        "id": "rx-4104-xw",
        "name": "RX-4104-XW",
        "imageUrl": "/images/collections/adapta/polaris/orion/rx-4104-xw.webp"
      },
      {
        "id": "rx-5114-xw",
        "name": "RX-5114-XW",
        "imageUrl": "/images/collections/adapta/polaris/orion/rx-5114-xw.webp"
      },
      {
        "id": "rx-6125-xw",
        "name": "RX-6125-XW",
        "imageUrl": "/images/collections/adapta/polaris/orion/rx-6125-xw.webp"
      },
      {
        "id": "rx-7177-xw",
        "name": "RX-7177-XW",
        "imageUrl": "/images/collections/adapta/polaris/orion/rx-7177-xw.webp"
      },
      {
        "id": "rx-8121-xw",
        "name": "RX-8121-XW",
        "imageUrl": "/images/collections/adapta/polaris/orion/rx-8121-xw.webp"
      },
      {
        "id": "rx-2107-xw",
        "name": "RX-2107-XW"
      }
    ]
  },
  {
    "id": "pegassus",
    "name": "Pegassus",
    "description": "Gris et neutres métalliques à fort caractère.",
    "finishes": [
      {
        "id": "rl-7193-x",
        "name": "RL-7193-X",
        "imageUrl": "/images/collections/adapta/polaris/pegassus/rl-7193-x.webp"
      },
      {
        "id": "rl-7125-x",
        "name": "RL-7125-X",
        "imageUrl": "/images/collections/adapta/polaris/pegassus/rl-7125-x.webp"
      },
      {
        "id": "rl-9939-x",
        "name": "RL-9939-X",
        "imageUrl": "/images/collections/adapta/polaris/pegassus/rl-9939-x.webp"
      },
      {
        "id": "rl-9940-x",
        "name": "RL-9940-X",
        "imageUrl": "/images/collections/adapta/polaris/pegassus/rl-9940-x.webp"
      },
      {
        "id": "rl-9941-x",
        "name": "RL-9941-X",
        "imageUrl": "/images/collections/adapta/polaris/pegassus/rl-9941-x.webp"
      }
    ]
  },
  {
    "id": "phoenix",
    "name": "Phoenix",
    "description": "Métalliques haute brillance aux reflets ardents.",
    "finishes": [
      {
        "id": "hx-7129-x",
        "name": "HX-7129-X",
        "imageUrl": "/images/collections/adapta/polaris/phoenix/hx-7129-x.webp"
      },
      {
        "id": "hx-7177-x",
        "name": "HX-7177-X",
        "imageUrl": "/images/collections/adapta/polaris/phoenix/hx-7177-x.webp"
      },
      {
        "id": "hx-7178-x",
        "name": "HX-7178-X",
        "imageUrl": "/images/collections/adapta/polaris/phoenix/hx-7178-x.webp"
      },
      {
        "id": "hx-7159-x",
        "name": "HX-7159-X",
        "imageUrl": "/images/collections/adapta/polaris/phoenix/hx-7159-x.webp"
      },
      {
        "id": "hf-7164-x",
        "name": "HF-7164-X",
        "imageUrl": "/images/collections/adapta/polaris/phoenix/hf-7164-x.webp"
      },
      {
        "id": "hf-7188-x",
        "name": "HF-7188-X",
        "imageUrl": "/images/collections/adapta/polaris/phoenix/hf-7188-x.webp"
      },
      {
        "id": "hx-7210-x",
        "name": "HX-7210-X",
        "imageUrl": "/images/collections/adapta/polaris/phoenix/hx-7210-x.webp"
      },
      {
        "id": "hx-1531-x",
        "name": "HX-1531-X",
        "imageUrl": "/images/collections/adapta/polaris/phoenix/hx-1531-x.webp"
      },
      {
        "id": "hx-8116-x",
        "name": "HX-8116-X",
        "imageUrl": "/images/collections/adapta/polaris/phoenix/hx-8116-x.webp"
      }
    ]
  },
  {
    "id": "hydra",
    "name": "Hydra",
    "description": "Nuances de gris métalliques structurés.",
    "finishes": [
      {
        "id": "rx-9006-x",
        "name": "RX-9006-X",
        "imageUrl": "/images/collections/adapta/polaris/hydra/rx-9006-x.webp"
      },
      {
        "id": "rx-9007-x",
        "name": "RX-9007-X",
        "imageUrl": "/images/collections/adapta/polaris/hydra/rx-9007-x.webp"
      },
      {
        "id": "rx-7167-x",
        "name": "RX-7167-X",
        "imageUrl": "/images/collections/adapta/polaris/hydra/rx-7167-x.webp"
      },
      {
        "id": "rx-7141-tz",
        "name": "RX-7141-TZ",
        "imageUrl": "/images/collections/adapta/polaris/hydra/rx-7141-tz.webp"
      },
      {
        "id": "rx-7100-tz",
        "name": "RX-7100-TZ",
        "imageUrl": "/images/collections/adapta/polaris/hydra/rx-7100-tz.webp"
      },
      {
        "id": "rx-7191-x",
        "name": "RX-7191-X",
        "imageUrl": "/images/collections/adapta/polaris/hydra/rx-7191-x.webp"
      },
      {
        "id": "rx-7168-x",
        "name": "RX-7168-X"
      }
    ]
  }
];

export const ADAPTA_DICHROIC_FINISHES: AdaptaFinish[] = [
  {
    "id": "d-and-500",
    "name": "D & 500",
    "imageUrl": "/images/collections/adapta/dichroic/d-and-500.webp"
  },
  {
    "id": "odd-and-even",
    "name": "ODD & EVEN",
    "imageUrl": "/images/collections/adapta/dichroic/odd-and-even.webp"
  },
  {
    "id": "bonnie-and-clyde",
    "name": "BONNIE & CLYDE",
    "imageUrl": "/images/collections/adapta/dichroic/bonnie-and-clyde.webp"
  },
  {
    "id": "heads-and-tails",
    "name": "HEADS & TAILS",
    "imageUrl": "/images/collections/adapta/dichroic/heads-and-tails.webp"
  },
  {
    "id": "sky-and-dreams",
    "name": "SKY & DREAMS",
    "imageUrl": "/images/collections/adapta/dichroic/sky-and-dreams.webp"
  },
  {
    "id": "lucky-and-unlucky",
    "name": "LUCKY & UNLUCKY",
    "imageUrl": "/images/collections/adapta/dichroic/lucky-and-unlucky.webp"
  },
  {
    "id": "side-and-side",
    "name": "SIDE & SIDE",
    "imageUrl": "/images/collections/adapta/dichroic/side-and-side.webp"
  },
  {
    "id": "ebony-and-ivory",
    "name": "EBONY & IVORY",
    "imageUrl": "/images/collections/adapta/dichroic/ebony-and-ivory.webp"
  },
  {
    "id": "up-and-down",
    "name": "UP & DOWN",
    "imageUrl": "/images/collections/adapta/dichroic/up-and-down.webp"
  },
  {
    "id": "gold-and-silver",
    "name": "GOLD & SILVER",
    "imageUrl": "/images/collections/adapta/dichroic/gold-and-silver.webp"
  },
  {
    "id": "garuda-and-adurag",
    "name": "GARUDA & ADURAG",
    "imageUrl": "/images/collections/adapta/dichroic/garuda-and-adurag.webp"
  },
  {
    "id": "tantima-and-amitant",
    "name": "TANTIMA & AMITANT",
    "imageUrl": "/images/collections/adapta/dichroic/tantima-and-amitant.webp"
  },
  {
    "id": "red-and-fire",
    "name": "RED & FIRE",
    "imageUrl": "/images/collections/adapta/dichroic/red-and-fire.webp"
  },
  {
    "id": "yin-and-yang",
    "name": "YIN & YANG",
    "imageUrl": "/images/collections/adapta/dichroic/yin-and-yang.webp"
  },
  {
    "id": "crazy-and-horse",
    "name": "CRAZY & HORSE",
    "imageUrl": "/images/collections/adapta/dichroic/crazy-and-horse.webp"
  },
  {
    "id": "pixie-and-dixie",
    "name": "PIXIE & DIXIE",
    "imageUrl": "/images/collections/adapta/dichroic/pixie-and-dixie.webp"
  },
  {
    "id": "queens-and-kings",
    "name": "QUEENS & KINGS",
    "imageUrl": "/images/collections/adapta/dichroic/queens-and-kings.webp"
  },
  {
    "id": "east-and-west",
    "name": "EAST & WEST",
    "imageUrl": "/images/collections/adapta/dichroic/east-and-west.webp"
  },
  {
    "id": "winners-and-losers",
    "name": "WINNERS & LOSERS",
    "imageUrl": "/images/collections/adapta/dichroic/winners-and-losers.webp"
  },
  {
    "id": "laurel-and-hardy",
    "name": "LAUREL & HARDY",
    "imageUrl": "/images/collections/adapta/dichroic/laurel-and-hardy.webp"
  },
  {
    "id": "guns-and-roses",
    "name": "GUNS & ROSES",
    "imageUrl": "/images/collections/adapta/dichroic/guns-and-roses.webp"
  },
  {
    "id": "dr-jekyll-and-mr-hide",
    "name": "DR. JEKYLL & MR. HIDE",
    "imageUrl": "/images/collections/adapta/dichroic/dr-jekyll-and-mr-hide.webp"
  },
  {
    "id": "on-and-off",
    "name": "ON & OFF",
    "imageUrl": "/images/collections/adapta/dichroic/on-and-off.webp"
  },
  {
    "id": "rock-and-roll",
    "name": "ROCK & ROLL",
    "imageUrl": "/images/collections/adapta/dichroic/rock-and-roll.webp"
  }
];

export const ADAPTA_SFERA_FINISHES: AdaptaFinish[] = [
  {
    "id": "azul-caballa",
    "name": "azul caballa",
    "imageUrl": "/images/collections/adapta/sfera/azul-caballa.webp"
  },
  {
    "id": "negro-cosmos",
    "name": "negro cosmos",
    "imageUrl": "/images/collections/adapta/sfera/negro-cosmos.webp"
  },
  {
    "id": "plata-cosmos",
    "name": "plata cosmos",
    "imageUrl": "/images/collections/adapta/sfera/plata-cosmos.webp"
  },
  {
    "id": "rojo-fuego",
    "name": "rojo fuego",
    "imageUrl": "/images/collections/adapta/sfera/rojo-fuego.webp"
  },
  {
    "id": "azul-anod",
    "name": "azul anod.",
    "imageUrl": "/images/collections/adapta/sfera/azul-anod.webp"
  },
  {
    "id": "cobre-anod",
    "name": "cobre anod.",
    "imageUrl": "/images/collections/adapta/sfera/cobre-anod.webp"
  },
  {
    "id": "verde-anod",
    "name": "verde anod.",
    "imageUrl": "/images/collections/adapta/sfera/verde-anod.webp"
  },
  {
    "id": "laton-anod",
    "name": "latón anod.",
    "imageUrl": "/images/collections/adapta/sfera/laton-anod.webp"
  },
  {
    "id": "acero-anod",
    "name": "acero anod.",
    "imageUrl": "/images/collections/adapta/sfera/acero-anod.webp"
  },
  {
    "id": "bronce-anod",
    "name": "bronce anod.",
    "imageUrl": "/images/collections/adapta/sfera/bronce-anod.webp"
  },
  {
    "id": "gris-plata-anod",
    "name": "gris plata anod.",
    "imageUrl": "/images/collections/adapta/sfera/gris-plata-anod.webp"
  },
  {
    "id": "plata-anod",
    "name": "plata anod.",
    "imageUrl": "/images/collections/adapta/sfera/plata-anod.webp"
  },
  {
    "id": "azul-artico",
    "name": "azul ártico",
    "imageUrl": "/images/collections/adapta/sfera/azul-artico.webp"
  }
];
